name: Release

description: Release a new version of the project

inputs:
  token:
    description: GitHub token
    required: true
  dry-run:
    description: Dry run the release
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Release
      id: next-version
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        if [ "${{ inputs.dry-run }}" == "true" ]; then
          pnpm exec semantic-release --dry-run
        else
          pnpm exec semantic-release
        fi
