export enum APP_ERROR {
  UNKNOWN_ERROR = 1,
  INVALID_PAYLOAD = 2,
  UNAUTHORIZED = 3,
  MODEL_NOT_FOUND = 4,
  FORBIDDEN = 5,
  NOT_IMPLEMENTED = 6,
  EMPTY_TOKEN = 7,
  INVALID_TOKEN = 8,
  ROUTE_NOT_FOUND = 9,
  PRISMA_ERROR = 10,
  EXPIRED_TOKEN = 11,
  BAD_CREDENTIALS = 12,
  INVALID_REFRESH_TOKEN = 13,
  EXPIRED_REFRESH_TOKEN = 14,
  MISSING_REFRESH_TOKEN = 15,

  CORN_RATE_LIMIT = 100,
}
